### ISSUE TITLE
Can we pretend that airplanes in the night sky are like shootin' stars

### ISSUE THREAD

**Issue by glorbatron** [authenyoo/authenyoo#4]
I could really use a wish right now, wish right now, wish right now

**Comment by authenyoo** [comment]
thats not right

**Comment by glorbatron** [comment]
DM and Home icon invisible with Windows High Contrast enabled #1578

Describe the bug
When using Cinny with Windows High Contrast enabled, the Direct Message and Home icons are completely invisible.

Reproduction
Enable Windows High Contrast mode.
Open Cinny.in in a web browser.
Navigate to the DM or Home section.
Expected behavior
The Direct Message and Home icons should be visible and distinguishable with Windows High Contrast enabled.

Platform and versions
OS: Windows 10, Windows 11
Browser: Firefox 120.0.1, Chrome 120.0.6099.71 
Cinny Version: v3.2.0 (app.cinny.in)
Additional context
No response

**Comment by authenyoo** [comment]
incorrect

**Comment by glorbatron** [comment]
> incorrect

h

**Comment by voxel79** [comment]
narshnellow fluff
